version: "3"

volumes:
  mongodb_data:
    external: false

networks:
  cocoannotator:
    external: false

services:
  webserver:
    ports:
      - "5000:5000"
    environment:
      - NAME=Test Annotator
  workers:
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
    ports:
      - 5555:5555
  messageq:
    ports:
      - 5672:5672
  database:
    ports:
      - "27017:27017"