version: "3"

volumes:
  mongodb_data:
    external: false

networks:
  cocoannotator:
    external: false

  core_ifu-net:
    external: true  

services:
  webserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: jsbroks/coco-annotator:webserver-stable
    container_name: annotator_webclient
    restart: always
    environment:
      - VIRTUAL_HOST=coco.ifu.vn
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=coco.ifu.vn
      - SECRET_KEY=RandomSecretKeyHere
      - FILE_WATCHER=true
    volumes:
      - "./datasets:/datasets"
      - "./models:/models"
    depends_on:
      - database
      - workers
    networks:
      - cocoannotator
      - core_ifu-net
  workers:
    container_name: annotator_workers
    build:
      context: .
      dockerfile: ./backend/workers/Dockerfile
    image: jsbroks/coco-annotator:workers-stable
    volumes:
      - "./datasets:/datasets"
    depends_on:
      - messageq
      - database
    networks:
      - cocoannotator
      - core_ifu-net
  messageq:
    image: rabbitmq:3
    container_name: annotator_message_q
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - cocoannotator
      - core_ifu-net
  database:
    image: mongo:4.0
    container_name: annotator_mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "mongodb_data:/data/db"
    command: "mongod --smallfiles --logpath=/dev/null"
    networks:
      - cocoannotator
      - core_ifu-net

